version: "3.3"
services:
    #proxy
    nginx:
        image: nginx
        container_name: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./proxy/conf.d:/etc/nginx/conf.d
            - ./proxy/vhost.d:/etc/nginx/vhost.d
            - ./proxy/html:/usr/share/nginx/html
            - ./proxy/certs:/etc/nginx/certs:ro
        networks:
            - proxy-tier

    #proxy-file-generator
    nginx-gen:
        image: jwilder/docker-gen
        container_name: nginx-gen
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
        volumes_from:
            - nginx
        entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

    #letsencrypt
    letsencrypt-nginx-proxy-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: letsencrypt-companion
        depends_on: [nginx-gen]
        volumes_from:
            - nginx
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./proxy/certs:/etc/nginx/certs:rw
        environment:
            - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

    #app
    nextcloud:
        image: wonderfall/nextcloud
        container_name: nextcloud
        links:
            - db_nextcloud:db_nextcloud
        environment:
            - UID=1000
            - GID=1000
        volumes:
            - ./nextcloud/data:/data
            - ./nextcloud/config:/config
            - ./nextcloud/apps:/apps2
        environment:
            - VIRTUAL_HOST=domain_name
            - VIRTUAL_NETWORK=nginx-proxy
            - VIRTUAL_PORT=80
            - LETSENCRYPT_HOST=domain_name
            - LETSENCRYPT_EMAIL=certificate_mail_address
        networks:
            - proxy-tier
        depends_on:
            - letsencrypt-nginx-proxy-companion
    db_nextcloud: #database
        image: mariadb:10
        container_name: db_nextcloud
        volumes:
            - ./nextcloud/db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root_password
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
            - MYSQL_PASSWORD=database_password
        networks:
            - proxy-tier
        depends_on:
            - letsencrypt-nginx-proxy-companion
networks:
    proxy-tier:
        external:
        name: nginx-proxy
