version: '3'

services:

  collabora:
    image: collabora/code:latest
    container_name: nextcloud-collab
    networks:
      - nextcloud_network
    cap_add:
     - MKNOD
    ports:
      - 127.0.0.1:9980:9980
    environment:
      - domain=drive\\.bitsbeat\\.com
      - username=admin
      - password=PASSWORD-EXAMPLE
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
      - VIRTUAL_HOST=office.bitsbeat.com
      - LETSENCRYPT_HOST=office.bitsbeat.com
      - LETSENCRYPT_EMAIL=shramik.awale@bitsbeat.com
    restart: unless-stopped

networks:
  nextcloud_network:
